[project]
name = "template-python-fastapi-in-vercel"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.125.0",
    "pydantic>=2.12.5",
    "uvicorn[standard]>=0.38.0",
]
